### ISSUE TITLE
Does the camera work properly?

### ISSUE THREAD

**Issue by yipsuiwah** [0ranko0P/GL62M-7RD-Hackintosh#2]

**Comment by 0ranko0P** [comment]
The built-in camera should work out of the box, maybe you just simply forgot to enable it(**FN+F6**).

**Comment by jbwharris** [comment]
Try opening Photo Booth, then pressing Function + F6 as suggested.

**Comment by yipsuiwah** [comment]
![Screen Shot 2021-05-21 at 10 52 09 PM](https://user-images.githubusercontent.com/56329256/119156873-36f04780-ba87-11eb-8e4c-472b2649ac2a.png)
![Screen Shot 2021-05-21 at 10 52 18 PM](https://user-images.githubusercontent.com/56329256/119156876-38ba0b00-ba87-11eb-923e-c20210979bed.png)

Can't find camera in usb
here is my [EFI](https://github.com/yipsuiwah/GL62M-7RD-Hackintosh)

**Comment by yipsuiwah** [comment]
I once turned off the camera under Windows. Does it matter?

**Comment by jbwharris** [comment]
Have you mapped your USB ports?

**Comment by 0ranko0P** [comment]
Updated to OC 0.6.9 yesterday b0678c6,  and you should use my configs instead of trying to solve the problem that I already solved before.

**Comment by yipsuiwah** [comment]
Thanks.My camera is working.
